services:
  # Next.js App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-feedback
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/product_feedback
    depends_on:
      - postgres

  # Database
  postgres:
    image: postgres:16-alpine
    container_name: product-feedback-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_feedback
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: